name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiple script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print
          (platform.processor())
        shell: python   //set the specific shell to use

  run-windows-commands:
    runs-on: windows-latest
    //usually, the jobs are run parallelly, the jobs' run can be ordered by adding dependences
    needs: ["run-shell-command"]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Direcotry Bash
        run: pwd
        shell: bash
