name: Simple Action
on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After
        run: |
          echo GITHUB_SHA
          echo GITHUB_REPOSITORY
          echo GITHIB_WORKSPACE
          echo "{{ github.token }}"
          pwd
          ls -a
