name: branch test with PR master
on:
  pull_request:
    branches:
      - master
      - "feature/*" #matches feature/featA,feature/featB,not match feature/feat/a
      - "feature/**" #matches all feature/*/*...
jobs:
  run-branch-test-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v1
      - name: List Files After
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHIB_WORKSPACE
          echo "${{ github.token }}"
          pwd
          ls -a

